---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hidupban/laravel_data_directory/hidupbanyakrasa-core
    - /bin/rm -rf $DEPLOYPATH/app
    - /bin/rm -rf $DEPLOYPATH/resources
    - /bin/rm -rf $DEPLOYPATH/routes
    - /bin/rm -rf $DEPLOYPATH/config
    - /bin/rm -rf $DEPLOYPATH/lang
    - /bin/rm -rf $DEPLOYPATH/bootstrap
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/vendor
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -rf $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/.gitignore
    - /opt/cpanel/ea-php82/root/usr/bin/php ~/bin/composer install --no-dev
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan cache:clear
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan view:clear

